name: Sync Fluent recipes

on:
  workflow_dispatch:
  schedule:
    - cron: "10 6,12,18 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run sync script (download missing recipes)
        run: |
          python .github/scripts/sync_recipes.py

      - name: Check for recipe changes
        id: diff
        run: |
          CHANGES=$(git status --porcelain recipes)
          if [ -n "$CHANGES" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push changes to main
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git remote set-url origin "https://x-access-token:${REPO_TOKEN}@github.com/${{ github.repository }}.git"

          git add recipes
          git commit -m "Sync missing Fluent migrations" || { echo "Nothing to commit"; exit 0; }
          git push origin HEAD:main

      - name: Comment on firefox-l10n-source open PR about pending migrations
        if: steps.diff.outputs.changed == 'true'
        run: |
          python .github/scripts/comment_pr.py
